name: Fisrt-Demo
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: Print step
          run: |
            echo "Hello World 1"
            echo "Hello World 2"
            echo "Hello World 3"